/* eslint-disable */
// GENERATED by web-showcase/scripts/gen-types.mjs from shared/schema/*.schema.json.
// Do not edit by hand: change the Pydantic models, run `python -m omnisight_contracts.export_schema`,
// then `npm run gen:types`.

export const CONTRACT_VERSION = "2.1.0";

export type DataB64 = string

export type DurationMs = number

export type Mime = "audio/wav"

export type SampleRate = number

export type Kind = ("desktop" | "web" | "benchmark" | "test")

export type Platform = string

export type Version = string
/**
 * Standard base64 (RFC 4648) without a data-URL prefix.
 */

export type DataB641 = string

export type Height = number

export type Mime1 = ("image/jpeg" | "image/png" | "image/webp")

export type Width = number

export type MaxNewTokens = number
/**
 * What the user wants from the captured screen.
 */

export type AnalysisMode = ("explain" | "debug" | "summarize" | "ocr" | "voice_query")

export type Prompt = string

export type RequestId = string
/**
 * Sampling temperature; 0 selects greedy decoding.
 */

export type Temperature = number

/**
 * Body of ``POST /v1/analyze``.
 */

export interface AnalyzeRequest {
audio?: (AudioPayload | null)
client?: (ClientInfo | null)
image: ImagePayload
max_new_tokens?: MaxNewTokens
mode?: AnalysisMode
prompt?: Prompt
request_id?: RequestId
temperature?: Temperature
}
/**
 * A push-to-talk voice clip (16-bit PCM WAV).
 */

export interface AudioPayload {
data_b64: DataB64
duration_ms: DurationMs
mime?: Mime
sample_rate: SampleRate
}
/**
 * Identifies the calling surface for telemetry and debugging.
 */

export interface ClientInfo {
kind: Kind
platform?: Platform
version: Version
}
/**
 * A single compressed screenshot, base64 encoded.
 */

export interface ImagePayload {
data_b64: DataB641
height: Height
mime: Mime1
width: Width
}

export type Code = string

export type Language = string
/**
 * @maxItems 50
 */

export type CodeBlocks = CodeBlock[]
/**
 * Geometric-mean probability of the generated tokens under the raw model distribution; null when the producing backend cannot measure it.
 */

export type Confidence = (number | null)

export type ContractVersion = string

export type CreatedUtc = string

export type DetectedLanguage = (string | null)

export type FinishReason = ("stop" | "length" | "timeout")

export type Markdown = string

export type ModelId = string

export type Source = ("kaggle" | "gemini" | "deterministic")

export type Summary = string

export type QueueMs = number

export type TokensGenerated = number

export type TokensPerSec = number

export type TotalMs = number
/**
 * Time to first generated token.
 */

export type TtftMs = number
/**
 * ASR text for voice queries.
 */

export type Transcript = (string | null)

/**
 * Successful body of ``POST /v1/analyze`` (and of the web fallback route).
 */

export interface AnalyzeResponse {
code_blocks?: CodeBlocks
confidence?: Confidence
contract_version?: ContractVersion
created_utc?: CreatedUtc
detected_language?: DetectedLanguage
finish_reason?: FinishReason
markdown: Markdown
model_id: ModelId
request_id: RequestId
source: Source
summary: Summary
timings: InferenceTimings
transcript?: Transcript
}
/**
 * A fenced code block extracted from the model's markdown answer.
 */

export interface CodeBlock {
code: Code
language?: Language
}
/**
 * Latency and throughput measurements for one generation.
 */

export interface InferenceTimings {
queue_ms?: QueueMs
tokens_generated: TokensGenerated
tokens_per_sec: TokensPerSec
total_ms: TotalMs
ttft_ms: TtftMs
}

export type GpuDevice = string

export type Model = string

export type OmnisightEndpoint = string

export type Status = ("starting" | "online" | "offline")

export type UpdatedAt = string

/**
 * Live tunnel location published by the Kaggle node to the public gist.
 * 
 * The field names are the fixed gist schema::
 * 
 *     {
 *       "omnisight_endpoint": "https://<subdomain>.trycloudflare.com",
 *       "model": "Qwen2-VL-7B-Instruct-4bit",
 *       "status": "online",
 *       "updated_at": "<ISO-8601-UTC-Timestamp>",
 *       "gpu_device": "Tesla T4 16GB"
 *     }
 * 
 * The gist is world-readable: this model must never carry credentials.
 * Contract compatibility is checked through ``GET /v1/health``, not here.
 */

export interface EndpointRecord {
gpu_device: GpuDevice
model: Model
omnisight_endpoint: OmnisightEndpoint
status: Status
updated_at: UpdatedAt
}

export type Details = string[]
/**
 * Machine-readable failure categories returned in ``ErrorResponse``.
 */

export type ErrorCode = ("invalid_payload" | "payload_too_large" | "unauthorized" | "model_loading" | "gpu_oom" | "inference_timeout" | "upstream_unavailable" | "rate_limited" | "internal_error" | "not_found" | "method_not_allowed")

export type Message = string

export type RequestId2 = (string | null)

export type RetryAfterS = (number | null)

export type Retryable = boolean

/**
 * Body returned with every non-2xx status from the inference node.
 */

export interface ErrorResponse {
details?: Details
error_code: ErrorCode
message: Message
request_id?: RequestId2
retry_after_s?: RetryAfterS
retryable?: Retryable
}

export type AsrLoaded = boolean

export type AsrModelId = (string | null)
/**
 * Allocation right after the model finished loading.
 */

export type BaselineVramMb = (number | null)

export type ComputeCapability = (string | null)

export type Detail = (string | null)

export type GpuAvailable = boolean

export type GpuCount = number

export type GpuName = (string | null)

export type ModelLoaded = boolean

export type OomEvents = number

export type Quantization = ("nf4" | "int8" | "fp16" | "bf16" | "none")

export type QueueDepth = number

export type ServerTimeUtc = string

export type Status2 = ("ok" | "loading" | "degraded")

export type UptimeS = number

export type VramAllocatedMb = number

export type VramCeilingMb = number

export type VramPeakMb = number

export type VramReservedMb = number

export type VramTotalMb = number
/**
 * Static conditions that do not affect serving (e.g. baseline VRAM over budget).
 * 
 * @maxItems 20
 */

export type Warnings = []|[string]|[string, string]|[string, string, string]|[string, string, string, string]|[string, string, string, string, string]|[string, string, string, string, string, string]|[string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]|[string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]

/**
 * Body of ``GET /v1/health``.
 * 
 * Every ``*_mb`` field is in decimal megabytes (10**6 bytes), measured with
 * ``torch.cuda.memory_allocated`` / ``memory_reserved`` (the CUDA context that
 * nvidia-smi additionally reports is not included).
 */

export interface HealthResponse {
asr_loaded?: AsrLoaded
asr_model_id?: AsrModelId
baseline_vram_mb?: BaselineVramMb
compute_capability?: ComputeCapability
contract_version?: ContractVersion
detail?: Detail
gpu_available: GpuAvailable
gpu_count?: GpuCount
gpu_name?: GpuName
model_id: ModelId
model_loaded: ModelLoaded
oom_events?: OomEvents
quantization: Quantization
queue_depth?: QueueDepth
server_time_utc?: ServerTimeUtc
status: Status2
uptime_s: UptimeS
vram_allocated_mb: VramAllocatedMb
vram_ceiling_mb?: VramCeilingMb
vram_peak_mb?: VramPeakMb
vram_reserved_mb: VramReservedMb
vram_total_mb: VramTotalMb
warnings?: Warnings
}
