// Generate src/lib/contracts.ts from the shared JSON Schemas (shared/schema/*.schema.json).
// The Python Pydantic models are the source of truth; this keeps the web types from drifting.
//
//   node scripts/gen-types.mjs           regenerate
//   node scripts/gen-types.mjs --check   exit 1 if contracts.ts is out of date (CI)
import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, "..", "..", "shared", "schema");
const outFile = join(here, "..", "src", "lib", "contracts.ts");

const banner =
  "/* eslint-disable */\n" +
  "// GENERATED by web-showcase/scripts/gen-types.mjs from shared/schema/*.schema.json.\n" +
  "// Do not edit by hand: change the Pydantic models, run `python -m omnisight_contracts.export_schema`,\n" +
  "// then `npm run gen:types`.\n\n";

const DECLARATION = /^export (?:interface|type) (\w+)/;
// Compare declarations without comments: each split block also carries the JSDoc of the next one.
const normalize = (block) =>
  block
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .trim();

const files = (await readdir(schemaDir)).filter((name) => name.endsWith(".schema.json")).sort();
/** name -> normalized body of the declaration already emitted under that name */
const emitted = new Map();
const chunks = [];
let contractVersion = "unknown";
let renamed = 0;

for (const file of files) {
  const schema = JSON.parse(await readFile(join(schemaDir, file), "utf8"));
  contractVersion = schema["x-contract-version"] ?? contractVersion;
  const ts = await compile(schema, schema.title, {
    bannerComment: "",
    additionalProperties: false,
    strictIndexSignatures: true,
    unreachableDefinitions: false,
    format: false,
  });
  let blocks = ts
    .split(/\n(?=export )/)
    .map((block) => block.trim())
    .filter((block) => DECLARATION.test(block));

  // Several schemas share $defs (e.g. CodeBlock) and json-schema-to-typescript names property
  // types after their titles, so the same name can mean different things in different files
  // (ErrorResponse.request_id is nullable, AnalyzeRequest.request_id is not). Identical
  // declarations are emitted once; a conflicting one is renamed within its own file.
  const renames = new Map();
  for (const block of blocks) {
    const name = DECLARATION.exec(block)[1];
    const previous = emitted.get(name);
    if (previous !== undefined && previous !== normalize(block)) {
      let suffix = 2;
      while (emitted.has(`${name}${suffix}`) || blocks.some((other) => DECLARATION.exec(other)[1] === `${name}${suffix}`)) suffix += 1;
      renames.set(name, `${name}${suffix}`);
    }
  }
  if (renames.size) {
    const pattern = new RegExp(`\\b(${[...renames.keys()].join("|")})\\b`, "g");
    blocks = blocks.map((block) => block.replace(pattern, (name) => renames.get(name)));
    renamed += renames.size;
  }

  for (const block of blocks) {
    const name = DECLARATION.exec(block)[1];
    if (emitted.has(name)) continue; // identical re-declaration from a shared $def
    emitted.set(name, normalize(block));
    chunks.push(block);
  }
}

const output = `${banner}export const CONTRACT_VERSION = ${JSON.stringify(contractVersion)};\n\n${chunks.join("\n\n")}\n`;
const summary = `${emitted.size} types, ${renamed} renamed to avoid collisions, contract ${contractVersion}`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = await readFile(outFile, "utf8");
  } catch {
    current = "";
  }
  if (current.replace(/\r\n/g, "\n") !== output) {
    console.error("src/lib/contracts.ts is out of date: run `npm run gen:types`.");
    process.exit(1);
  }
  console.log(`contracts.ts is current (${summary}).`);
} else {
  await writeFile(outFile, output, "utf8");
  console.log(`wrote ${outFile} (${summary}).`);
}
